// Stage the exact set of files that may be published, then let the static host
// serve only that folder.
//
// Why this exists: uploading a folder publishes its whole contents, and both
// .netlifyignore and .gitignore were ignored during the upload. Verified against
// the live Netlify site - these all returned HTTP 200 while listed in one file or
// the other:
//
//   /firebase/database.rules.json   (listed in .netlifyignore)
//   /package.json                   (listed in .netlifyignore)
//   /package-lock.json              (listed in .netlifyignore)
//   /scripts/seo-check.js           (listed in .netlifyignore)
//   /MIGRATION_GUIDE.md             (listed in .gitignore)
//
// The deploy payload is built from the folder contents, so the only reliable fix
// is to publish a directory that contains just the site. That is what this script
// produces, and wrangler.toml points pages_build_output_dir at it.
//
// Run: node scripts/build-publish.js
// Verify: node scripts/check-publish.js

import { readFile, readdir, mkdir, copyFile, rm, stat, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(root, 'public');

// Directories never copied into the publish output.
const EXCLUDED_DIRS = new Set([
  'node_modules',
  '.git',
  '.github',
  '.firebase',
  '.netlify',
  'public', // never recurse into our own output
  'tests',
  'scripts',
  'firebase'
]);

// Individual files that must not be published even at the repository root.
const EXCLUDED_FILES = new Set([
  '.firebaserc',
  '.gitignore',
  '.netlifyignore',
  '.node-version',
  'firebase.json',
  'netlify.toml',
  'wrangler.toml',
  'package.json',
  'package-lock.json',
  'playwright.config.js',
  'QA_REPORT.md',
  'MVP-AUDIT.md',
  'DEPLOYMENT_CHECKLIST.md',
  'MIGRATION_GUIDE.md',
  'README.md'
]);

const EXCLUDED_EXTENSIONS = new Set(['.docx', '.log', '.map', '.env']);

async function collect(dir, base = '') {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) continue;
      if (entry.name.startsWith('.') && entry.name !== '.well-known') continue;
      out.push(...(await collect(path.join(dir, entry.name), rel)));
      continue;
    }
    if (!entry.isFile()) continue;

    if (EXCLUDED_FILES.has(entry.name)) continue;
    if (entry.name.startsWith('.') && entry.name !== '.well-known') continue;
    if (EXCLUDED_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) continue;

    out.push(rel);
  }
  return out;
}

// Written into the publish output so Cloudflare Pages can cache the catalogue
// without the HTML pages going stale.
const HEADERS = `# Generated by scripts/build-publish.js - do not edit.
# firebase.json sets this for the old Firebase Hosting deploy; Pages does not
# read firebase.json, so the rule is restated here.
/products.json
  Cache-Control: public, max-age=600, stale-while-revalidate=300

# Self-hosted fonts never change under the same name.
/fonts/*
  Cache-Control: public, max-age=31536000, immutable

# Images and thumbnails: cached for a day and served stale while they refresh, so a
# vendor who changes a picture still sees it replaced within a day.
/Visuamall/*
  Cache-Control: public, max-age=86400, stale-while-revalidate=604800
/product/*.jpg
  Cache-Control: public, max-age=86400, stale-while-revalidate=604800
/product/thumb/*
  Cache-Control: public, max-age=86400, stale-while-revalidate=604800

# Stylesheet and scripts keep their names between releases, so they are revalidated
# quickly: a returning visitor gets the cached copy instantly and the new one next time.
/css/*
  Cache-Control: public, max-age=300, stale-while-revalidate=86400
/js/*
  Cache-Control: public, max-age=300, stale-while-revalidate=86400
`;

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  const files = (await collect(root)).sort();

  for (const rel of files) {
    const dest = path.join(OUT, rel);
    await mkdir(path.dirname(dest), { recursive: true });
    await copyFile(path.join(root, rel), dest);
  }

  // The SEO build writes generated HTML into the repository root, so those files
  // are copied above. Confirm the essentials survived the copy rather than
  // trusting the walk.
  const required = ['index.html', 'login.html', 'css/main.css', 'js/auth.js', 'sitemap.xml', 'robots.txt'];
  const missing = [];
  for (const rel of required) {
    if (!existsSync(path.join(OUT, rel))) missing.push(rel);
  }
  if (missing.length) {
    throw new Error(`publish output is incomplete, missing: ${missing.join(', ')}. Run "npm run build:seo" first.`);
  }

  const bytes = (await Promise.all(files.map(async (f) => (await stat(path.join(OUT, f))).size)))
    .reduce((a, b) => a + b, 0);

  // Cloudflare Pages reads header rules from a _headers file inside the publish
  // directory. firebase.json carried this same rule for the old Firebase Hosting
  // deploy, but Pages never reads firebase.json, so restate it here. It has to be
  // generated rather than committed because this script clears public/ first.
  await writeFile(path.join(OUT, '_headers'), HEADERS, 'utf8');

  console.log(`staged ${files.length} files (${(bytes / 1024).toFixed(0)} KB) into public/`);
  console.log('Cloudflare Pages will now serve public/ only. Run "npm run publish:check" to confirm nothing sensitive is inside.');
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});